name: Linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y libboost-test-dev
      - run: cd build && cmake .. -DBUILD_TESTING=true -DCMAKE_EXPORT_COMPILE_COMMANDS=true
        # export the database for cpp-lint so it can find boost
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extra-args: -std=c++17
          database: build
          tidy-checks: boost-*,\
            bugprone-*,\
            performance-*,\
            readability-*,\
            portability-*,\
            clang-analyzer-*,\
            cppcoreguidelines-*,\
            -readability-else-after-return,\
            -readability-implicit-bool-conversion,\
            -readability-named-parameter,\
            -readability-magic-numbers,\
            -readability-uppercase-literal-suffix,\
            -readability-function-cognitive-complexity,\
            -cppcoreguidelines-avoid-magic-numbers,\
            -cppcoreguidelines-macro-usage,\
            -cppcoreguidelines-pro-bounds-pointer-arithmetic,\
            -cppcoreguidelines-pro-type-cstyle-cast,\
            -cppcoreguidelines-avoid-c-arrays,\
            -cppcoreguidelines-pro-bounds-array-to-pointer-decay,\
            -cppcoreguidelines-pro-bounds-constant-array-index,\
            -cppcoreguidelines-avoid-non-const-global-variables,\
            -cppcoreguidelines-owning-memory,\
            -cppcoreguidelines-avoid-goto,\
            -cppcoreguidelines-pro-type-vararg

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!" ; exit 1
