name: Tests

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-test-dev cmake pkg-config libpcre2-dev libncursesw5-dev libtbb-dev
      - name: Build project
        run: |
          cd build
          cmake .. -DBUILD_TESTING=true
          cmake --build . --target unit_tests
      - name: Run Tests
        run: cd build && ctest
